@host = http://localhost:8080

# Fluxo manual atualizado:
# 1. Criar pauta
# 2. Abrir sessao
# 3. Consultar tela mobile de voto
# 4. Registrar votos
# 5. Consultar resultado
#
# Contrato atual:
# - POST /votos retorna apenas protocolo, pautaId e status=REGISTRADO
# - GET /resultado durante a sessao retorna status=EM_ANDAMENTO sem totalSim/totalNao
# - totais so devem ser divulgados apos o fechamento da sessao

###
GET {{host}}/mobile/v1/pautas/nova

###
# @name criarPauta
POST {{host}}/v1/pautas
Content-Type: application/json

{
  "descricao": "Assembleia Geral Extraordinaria - Dezembro/2026"
}

@pautaId = {{criarPauta.response.body.id}}

###
GET {{host}}/v1/pautas/{{pautaId}}

###
POST {{host}}/v1/pautas/{{pautaId}}/sessoes
Content-Type: application/json

{
  "duracaoMinutos": 10
}

###
GET {{host}}/mobile/v1/pautas/{{pautaId}}/votos/selecao

###
# Valido com CPF 87868790067
POST {{host}}/v1/pautas/{{pautaId}}/votos
Content-Type: application/json

{
  "associadoId": "87868790067",
  "votoEscolha": "SIM"
}

###
# Retorno esperado:
# {
#   "protocolo": "<uuid>",
#   "pautaId": "<uuid>",
#   "status": "REGISTRADO"
# }

###
# Valido com CPF 98189135074
POST {{host}}/v1/pautas/{{pautaId}}/votos
Content-Type: application/json

{
  "associadoId": "98189135074",
  "votoEscolha": "NAO"
}

###
# Valido com CPF 11933950030
POST {{host}}/v1/pautas/{{pautaId}}/votos
Content-Type: application/json

{
  "associadoId": "11933950030",
  "votoEscolha": "SIM"
}

###
# Valido com CPF 57376476091
POST {{host}}/v1/pautas/{{pautaId}}/votos
Content-Type: application/json

{
  "associadoId": "57376476091",
  "votoEscolha": "NAO"
}

###
# Valido com CPF 00000000191
POST {{host}}/v1/pautas/{{pautaId}}/votos
Content-Type: application/json

{
  "associadoId": "00000000191",
  "votoEscolha": "SIM"
}

###
# Invalido com CPF 12345678912
POST {{host}}/v1/pautas/{{pautaId}}/votos
Content-Type: application/json

{
  "associadoId": "12345678912",
  "votoEscolha": "SIM"
}

###
# Enquanto a sessao estiver aberta, o retorno esperado e:
# {
#   "pautaId": "<uuid>",
#   "totalSim": null,
#   "totalNao": null,
#   "status": "EM_ANDAMENTO"
# }
GET {{host}}/v1/pautas/{{pautaId}}/resultado

###
# @name criarPautaExpirada
POST {{host}}/v1/pautas
Content-Type: application/json

{
  "descricao": "Pauta Relampago para Teste de Timeout"
}

@pautaExpiradaId = {{criarPautaExpirada.response.body.id}}

###
POST {{host}}/v1/pautas/{{pautaExpiradaId}}/sessoes
Content-Type: application/json

{
  "duracaoMinutos": 1
}

###
POST {{host}}/v1/pautas/{{pautaExpiradaId}}/votos
Content-Type: application/json

{
  "associadoId": "87868790067",
  "votoEscolha": "SIM"
}
